config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, only: [:show, :index, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:email]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.order(created_at: :desc)
    @book = Book.new
    @book.user_id = current_user.id
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def create
    @books = Book.all.order(created_at: :desc)
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    user_path(resource)
  end 
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
    @user = current_user
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.order(created_at: :desc)
  end
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
  <!--User info開始-->
  <h2>User info</h2>
  <div class="profile-container">
    <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %>
    <table class="table">
      <tbody><tr></tr>
        <tr>
          <th>name</th>
          <th><%= @book.user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @book.user.introduction %></th>
        </tr>
      </tbody></table>
    </table>
    <div class="row">
      <a class="btn btn-outline-secondary btn-block fas fa-user-cog" href="/users/<%= @book.user.id %>/edit"></a>
    </div>
  </div>
  <!--User info終了-->
  <!--New book開始-->
  <h2 class="mt-3">New book</h2>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= form_with model: book, local:true do |f| %>
      <h6>Title</h6>
      <%= f.text_field :title %>
      <h6>Opinion</h6>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book', :class=>"btn btn-success" %>
    <% end %>
  </div>
  <!--New book終了-->
</div>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this obj from being saved:
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
        <div class="form-group">
          <h6>Title</h6>
          <%= f.text_area :title %>
        </div>
        <div class="form-group">
          <h6>Opinion</h6>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', :class=>"btn btn-success" %>
        </div>
      <% end %>
      <a><%= link_to "Show", book_path %></a> |
  		<a><%= link_to "Back", books_path %></a>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--User info、New book開始-->
    <%= render 'books/list', book: @book %>
    <!--User info、New book終了-->
    <!--Books開始-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
          </tr>
       </thead>
       <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to attachment_image_tag(book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60"), "/users/#{book.user.id}" %></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td class="favorite-btn"><%= render "favorites/favorite", book: book %></td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <!--Books終了-->
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--User info、New book開始-->
    <%= render 'books/list', book: @book_new %>
    <!--User info、New book終了-->
    <!--Book detail開始-->
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %><br>
              <%= link_to @book.user.name, user_path(@book.user) %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <td class="favorite-btn"><%= render "favorites/favorite", book: @book %></td>
            <td>
              <% if @book.user == current_user %>
              <a class="btn btn-sm btn-success" href="/books/<%= @book.id %>/edit">Edit</a>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
              <a data-confirm="本当に消しますか？" class="btn btn-sm btn-danger" rel="nofollow" data-method="delete" href="/books/<%= @book.id %>">Destroy</a>
              <% end %>
            </td>
            <td>コメント数：<%= @book.book_comments.count %></td>
          </tr>
        </tbody>
      </table>
      <div class="comments">
        <% @book.book_comments.each do |book_comment| %>
          <p><%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></p>
          <%= link_to book_comment.user.name, user_path(book_comment.user) %>
          <%= book_comment.comment %>
          <% if book_comment.user == current_user %>
            <%= link_to book_book_comment_path(book_comment.book, book_comment), method: :delete do %>
              <i class="btn btn-sm btn-danger" >Destroy</i>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="new-comment">
          <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
            <%= f.text_area :comment, cols:'90' %>
            <%= f.submit "送信する" %>
          <% end %>
      </div>
    </div>
    <!--Book detail終了-->
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, class: "fas fa-heart heart_blue" %>
<% end %>

app/views/users/_list.html.erb
<div class="col-md-3">
  <!--User info開始-->
  <h2>User info</h2>
  <div class="profile-container">
    <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %>
    <table class="table">
      <tbody><tr></tr>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </tbody></table>
    </table>
    <div class="row">
      <a class="btn btn-outline-secondary btn-block fas fa-user-cog" href="/users/<%= @user.id %>/edit"></a>
    </div>
  </div>
  <!--User info終了-->
  <!--New book開始-->
  <h2 class="mt-3">New book</h2>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved:
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= form_with model: @book, local:true do |f| %>
      <h6>Title</h6>
      <%= f.text_field :title %>
      <h6>Opinion</h6>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book', :class=>"btn btn-success" %>
    <% end %>
  </div>
  <!--New book終了-->
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User Info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <h6>Name</h6>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <h6>Image</h6>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form-group">
          <h6>Introduction</h6>
          <%= f.text_area :introduction %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', :class=>"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--User info、New book開始-->
    <%= render 'users/list', user: @user %>
    <!--User info、New book終了-->
    <!--Users開始-->
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
      　<thead>
          <tr>
            <th></th>
          　<th>image</th>
          　<th>name</th>
          　<th colspan="3"></th>
          </tr>
      　</thead>
      　<tbody>
          <% @users.each do |user| %>
            <tr>
            　<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></td>
            　<td><%= user.name %></td>
            　<td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
      　</tbody>
      </table>
    </div>
    <!--Users終了-->
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <!--User info、New book開始-->
    <%= render 'users/list', user: @user %>
    <!--User info、New book終了-->
    <!--UserBooks開始-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
      　<thead>
          <tr>
            <th></th>
          　<th>Title</th>
          　<th>Body</th>
          　<th colspan="3"></th>
          </tr>
      　</thead>
      　<tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to attachment_image_tag(book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60"), "/users/#{book.user.id}" %></td>
          　<td><%= link_to book.title, book_path(book) %></td>
          　<td><%= book.body %></td>
          </tr>
          <% end %>
      　</tbody>
      </table>
    </div>
    <!--UserBooks終了-->
  </div>
</div>